name: Test NIFTY 50 Momentum Analyzer

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 10:00 AM IST (4:30 AM UTC) during market hours
    - cron: '30 4 * * 1-5'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test connection to NSE
      run: |
        python test_connection.py

    - name: Run scraper
      run: |
        python scrape_nifty50.py

    - name: Verify output files
      run: |
        python -c "import os; assert os.path.exists('nifty50_stocks.json'), 'JSON file not created'"
        python -c "import os; assert os.path.exists('nifty50_stocks.csv'), 'CSV file not created'"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nifty50-data-${{ matrix.os }}-py${{ matrix.python-version }}
        path: |
          nifty50_stocks.json
          nifty50_stocks.csv

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install linting tools
      run: |
        pip install flake8 pylint
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics